// apps/miniapp/src/pages/notifications/index.tsx
import { useState } from 'react';
import { useDidShow } from '@tarojs/taro';
import { View, Text, Button } from '@tarojs/components';
import type { NotificationSummary } from '@app/shared';
import { apiRequest } from '@/lib/api-client';

export default function NotificationsPage() {
  const [items, setItems] = useState<NotificationSummary[]>([]);
  const [err, setErr] = useState<string | null>(null);

  async function refresh() {
    try {
      const data = await apiRequest<NotificationSummary[]>('/notifications');
      setItems(data);
      setErr(null);
    } catch (e: any) {
      setErr(e.message);
    }
  }

  useDidShow(() => {
    refresh();
  });

  async function markOne(id: string) {
    try {
      await apiRequest(`/notifications/${id}/read`, { method: 'POST' });
      await refresh();
    } catch (e: any) {
      setErr(e.message);
    }
  }

  async function markAll() {
    try {
      await apiRequest('/notifications/read-all', { method: 'POST' });
      await refresh();
    } catch (e: any) {
      setErr(e.message);
    }
  }

  return (
    <View style={{ padding: '24rpx' }}>
      <View
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
        }}
      >
        <Text style={{ fontSize: '32rpx', fontWeight: 'bold' }}>通知</Text>
        <Button size="mini" onClick={markAll}>
          全部已读
        </Button>
      </View>
      {err && (
        <Text style={{ color: '#d33', display: 'block', marginTop: '16rpx' }}>
          {err}
        </Text>
      )}
      <View style={{ marginTop: '16rpx' }}>
        {items.length === 0 && (
          <Text style={{ color: '#888' }}>暂无消息</Text>
        )}
        {items.map((n) => (
          <View
            key={n.id}
            onClick={() => !n.readAt && markOne(n.id)}
            style={{
              padding: '16rpx',
              border: '1rpx solid #eee',
              borderRadius: '6rpx',
              marginTop: '8rpx',
              background: n.readAt ? '#fafafa' : '#fffbe6',
            }}
          >
            <Text style={{ fontWeight: 'bold' }}>{n.title}</Text>
            <Text style={{ display: 'block', color: '#555' }}>{n.body}</Text>
            <Text style={{ display: 'block', color: '#999' }}>
              {new Date(n.createdAt).toLocaleString()}
              {n.readAt ? ' · 已读' : ''}
            </Text>
          </View>
        ))}
      </View>
    </View>
  );
}

// apps/miniapp-uni/src/pages/notifications/index.vue
<template>
  <view class="page">
    <NavBar :title="$t('pageTitle.notifications')">
      <template #right>
        <u-button
          size="mini"
          :text="$t('common.readAll')"
          @click="markAll"
        />
      </template>
    </NavBar>
    <view class="content p-24">
      <view v-if="list.loading.value === 'empty'" class="empty">
        <u-empty :text="$t('toast.noNotifications')" />
      </view>
      <view
        v-for="n in list.dataList.value"
        :key="n.id"
        class="noti-card"
        :class="{ unread: !n.readAt }"
        @click="onTap(n)"
      >
        <text class="noti-title">{{ n.title }}</text>
        <text class="noti-body block">{{ n.body }}</text>
        <text class="noti-meta block">
          {{ formatDate(n.createdAt) }}{{ n.readAt ? ' · 已读' : '' }}
        </text>
      </view>
    </view>
    <TabBar :current="3" />
    <CustomBottomArea />
  </view>
</template>

<script setup lang="ts">
import { onShow } from '@dcloudio/uni-app';
import NavBar from '@/components/nav-bar/nav-bar.vue';
import TabBar from '@/components/tab-bar/tab-bar.vue';
import CustomBottomArea from '@/components/custom-bottom-area/custom-bottom-area.vue';
import * as notificationsApi from '@/api/modules/notifications';
import { useRefreshList } from '@/hooks/useRefreshList';

interface Notification {
  id: string;
  title: string;
  body: string;
  createdAt: string;
  readAt?: string | null;
}

const list = useRefreshList<Notification>(() => notificationsApi.list(), {
  extract: (r: any) => ({
    records: r ?? [],
    total: r?.length ?? 0,
  }),
  pageSize: 9999,
});

async function onTap(n: Notification) {
  if (n.readAt) return;
  await notificationsApi.read(n.id);
  await list.fetchListRefresh();
}

async function markAll() {
  await notificationsApi.readAll();
  await list.fetchListRefresh();
}

function formatDate(ts: string) {
  try {
    return new Date(ts).toLocaleString();
  } catch {
    return ts;
  }
}

onShow(() => list.fetchListRefresh());
</script>

<style lang="scss" scoped>
.page {
  min-height: 100vh;
  background: #f5f5f5;
  padding-bottom: 120rpx;
}
.noti-card {
  background: #fafafa;
  border-radius: 16rpx;
  padding: 24rpx;
  margin-top: 16rpx;
}
.noti-card.unread {
  background: #fffbe6;
}
.noti-title {
  font-size: 28rpx;
  font-weight: 600;
  color: #1f2937;
}
.noti-body {
  margin-top: 8rpx;
  font-size: 26rpx;
  color: #4b5563;
}
.noti-meta {
  margin-top: 8rpx;
  font-size: 22rpx;
  color: #9ca3af;
}
.block {
  display: block;
}
.empty {
  display: flex;
  justify-content: center;
  padding: 64rpx 0;
}
</style>
