// apps/miniapp/src/pages/report-summary/index.tsx
import { useState, useCallback } from 'react';
import { useDidShow } from '@tarojs/taro';
import { View, Text, Button } from '@tarojs/components';
import {
  REPORT_SCOPE_MATRIX,
  type ReportType,
  type RoleCode,
  type UsageTrendResponse,
  type InventoryTurnoverResponse,
  type PurchaseAmountResponse,
} from '@app/shared';
import { apiRequest } from '@/lib/api-client';
import { useAuth } from '@/lib/auth-store';

interface CardState {
  label: string;
  value: string;
  loading: boolean;
  error: string | null;
}

const INITIAL: CardState = { label: '', value: '', loading: true, error: null };

export default function ReportSummaryPage() {
  const user = useAuth((s) => s.user);
  const roles = (user?.roles ?? []) as RoleCode[];

  const [usage, setUsage] = useState<CardState>({ ...INITIAL, label: '近 30 天领用量' });
  const [inv, setInv] = useState<CardState>({ ...INITIAL, label: '低库存数量' });
  const [purchase, setPurchase] = useState<CardState>({
    ...INITIAL,
    label: '本月采购金额',
  });

  const can = useCallback(
    (slug: ReportType) =>
      roles.some((r) => REPORT_SCOPE_MATRIX[r]?.[slug] != null),
    [roles],
  );

  async function loadUsage() {
    if (!can('usage-trend')) {
      setUsage((s) => ({ ...s, loading: false }));
      return;
    }
    setUsage((s) => ({ ...s, loading: true, error: null }));
    try {
      const d = await apiRequest<UsageTrendResponse>(
        '/reports/usage-trend?range=30d&summary=1',
      );
      setUsage({
        label: '近 30 天领用量',
        value: d.summary.totalIssued,
        loading: false,
        error: null,
      });
    } catch (e: any) {
      setUsage((s) => ({ ...s, loading: false, error: e.message ?? '加载失败' }));
    }
  }

  async function loadInv() {
    if (!can('inventory-turnover')) {
      setInv((s) => ({ ...s, loading: false }));
      return;
    }
    setInv((s) => ({ ...s, loading: true, error: null }));
    try {
      const d = await apiRequest<InventoryTurnoverResponse>(
        '/reports/inventory-turnover?range=30d&summary=1',
      );
      setInv({
        label: '低库存数量',
        value: String(d.summary.lowStockCount),
        loading: false,
        error: null,
      });
    } catch (e: any) {
      setInv((s) => ({ ...s, loading: false, error: e.message ?? '加载失败' }));
    }
  }

  async function loadPurchase() {
    if (!can('purchase-amount')) {
      setPurchase((s) => ({ ...s, loading: false }));
      return;
    }
    setPurchase((s) => ({ ...s, loading: true, error: null }));
    try {
      const d = await apiRequest<PurchaseAmountResponse>(
        '/reports/purchase-amount?range=month&groupBy=month&summary=1',
      );
      setPurchase({
        label: '本月采购金额(元)',
        value: d.summary.totalAmount,
        loading: false,
        error: null,
      });
    } catch (e: any) {
      setPurchase((s) => ({
        ...s,
        loading: false,
        error: e.message ?? '加载失败',
      }));
    }
  }

  function loadAll() {
    loadUsage();
    loadInv();
    loadPurchase();
  }

  useDidShow(() => {
    loadAll();
  });

  function renderCard(
    state: CardState,
    visible: boolean,
    retry: () => void,
  ) {
    if (!visible) return null;
    return (
      <View
        style={{
          marginTop: '24rpx',
          padding: '32rpx',
          border: '1rpx solid #ddd',
          borderRadius: '12rpx',
          background: '#fff',
        }}
      >
        <Text style={{ color: '#666', fontSize: '26rpx' }}>{state.label}</Text>
        {state.loading && (
          <Text style={{ display: 'block', marginTop: '16rpx', color: '#999' }}>
            加载中…
          </Text>
        )}
        {!state.loading && state.error && (
          <View style={{ marginTop: '16rpx' }}>
            <Text style={{ color: '#d4380d', fontSize: '26rpx' }}>
              {state.error}
            </Text>
            <Button
              size="mini"
              style={{ marginTop: '12rpx' }}
              onClick={retry}
            >
              点击重试
            </Button>
          </View>
        )}
        {!state.loading && !state.error && (
          <Text
            style={{
              display: 'block',
              marginTop: '16rpx',
              fontSize: '48rpx',
              fontWeight: 'bold',
            }}
          >
            {state.value || '—'}
          </Text>
        )}
      </View>
    );
  }

  return (
    <View style={{ padding: '32rpx', background: '#f5f5f5', minHeight: '100vh' }}>
      <Text style={{ fontSize: '36rpx', fontWeight: 'bold' }}>报表概览</Text>
      {renderCard(usage, can('usage-trend'), loadUsage)}
      {renderCard(inv, can('inventory-turnover'), loadInv)}
      {renderCard(purchase, can('purchase-amount'), loadPurchase)}
    </View>
  );
}

// apps/miniapp-uni/src/pages-sub/report-summary/index.vue
<template>
  <view class="page">
    <NavBar :title="$t('pageTitle.reportSummary')" showBack />
    <view class="content p-24">
      <view v-if="visibleCount === 0" class="empty">
        <u-empty :text="$t('report.noPermission')" />
      </view>

      <view v-if="canUsage" class="report-card">
        <text class="report-label">{{ usage.label }}</text>
        <view v-if="usage.loading" class="report-loading">
          <text class="muted">{{ $t('toast.loading') }}</text>
        </view>
        <view v-else-if="usage.error" class="report-error">
          <text class="error-text">{{ usage.error }}</text>
          <view class="mt-8">
            <u-button
              size="mini"
              :text="$t('common.retry')"
              @click="loadUsage"
            />
          </view>
        </view>
        <text v-else class="report-value">{{ usage.value || '—' }}</text>
      </view>

      <view v-if="canInv" class="report-card">
        <text class="report-label">{{ inv.label }}</text>
        <view v-if="inv.loading" class="report-loading">
          <text class="muted">{{ $t('toast.loading') }}</text>
        </view>
        <view v-else-if="inv.error" class="report-error">
          <text class="error-text">{{ inv.error }}</text>
          <view class="mt-8">
            <u-button
              size="mini"
              :text="$t('common.retry')"
              @click="loadInv"
            />
          </view>
        </view>
        <text v-else class="report-value">{{ inv.value || '—' }}</text>
      </view>

      <view v-if="canPurchase" class="report-card">
        <text class="report-label">{{ purchase.label }}</text>
        <view v-if="purchase.loading" class="report-loading">
          <text class="muted">{{ $t('toast.loading') }}</text>
        </view>
        <view v-else-if="purchase.error" class="report-error">
          <text class="error-text">{{ purchase.error }}</text>
          <view class="mt-8">
            <u-button
              size="mini"
              :text="$t('common.retry')"
              @click="loadPurchase"
            />
          </view>
        </view>
        <text v-else class="report-value">{{ purchase.value || '—' }}</text>
      </view>
    </view>
    <CustomBottomArea />
  </view>
</template>

<script setup lang="ts">
import { computed, reactive } from 'vue';
import { onShow } from '@dcloudio/uni-app';
import NavBar from '@/components/nav-bar/nav-bar.vue';
import CustomBottomArea from '@/components/custom-bottom-area/custom-bottom-area.vue';
import { useAuth } from '@/stores/auth';
import * as reportsApi from '@/api/modules/reports';
import { i18n } from '@/locale';
import {
  REPORT_SCOPE_MATRIX,
  type ReportType,
  type RoleCode,
} from '@app/shared';

interface CardState {
  label: string;
  value: string;
  loading: boolean;
  error: string | null;
}

const auth = useAuth();
const roles = computed<RoleCode[]>(() => (auth.user?.roles ?? []) as RoleCode[]);

function can(slug: ReportType) {
  return roles.value.some((r) => REPORT_SCOPE_MATRIX[r]?.[slug] != null);
}

const canUsage = computed(() => can('usage-trend'));
const canInv = computed(() => can('inventory-turnover'));
const canPurchase = computed(() => can('purchase-amount'));
const visibleCount = computed(
  () =>
    Number(canUsage.value) + Number(canInv.value) + Number(canPurchase.value),
);

const usage = reactive<CardState>({
  label: i18n.global.t('report.usageTrend'),
  value: '',
  loading: true,
  error: null,
});
const inv = reactive<CardState>({
  label: i18n.global.t('report.inventoryTurnover'),
  value: '',
  loading: true,
  error: null,
});
const purchase = reactive<CardState>({
  label: i18n.global.t('report.purchaseAmount'),
  value: '',
  loading: true,
  error: null,
});

async function loadUsage() {
  if (!canUsage.value) {
    usage.loading = false;
    return;
  }
  usage.loading = true;
  usage.error = null;
  try {
    const d: any = await reportsApi.usageTrend({ range: '30d', summary: 1 });
    usage.value = d?.summary?.totalIssued ?? '0';
  } catch (e: any) {
    usage.error = e?.message ?? i18n.global.t('toast.requestFailed');
  } finally {
    usage.loading = false;
  }
}

async function loadInv() {
  if (!canInv.value) {
    inv.loading = false;
    return;
  }
  inv.loading = true;
  inv.error = null;
  try {
    const d: any = await reportsApi.inventoryTurnover({
      range: '30d',
      summary: 1,
    });
    inv.value = String(d?.summary?.lowStockCount ?? '0');
  } catch (e: any) {
    inv.error = e?.message ?? i18n.global.t('toast.requestFailed');
  } finally {
    inv.loading = false;
  }
}

async function loadPurchase() {
  if (!canPurchase.value) {
    purchase.loading = false;
    return;
  }
  purchase.loading = true;
  purchase.error = null;
  try {
    const d: any = await reportsApi.purchaseAmount({
      range: 'month',
      groupBy: 'month',
      summary: 1,
    });
    purchase.value = d?.summary?.totalAmount ?? '0';
  } catch (e: any) {
    purchase.error = e?.message ?? i18n.global.t('toast.requestFailed');
  } finally {
    purchase.loading = false;
  }
}

function loadAll() {
  loadUsage();
  loadInv();
  loadPurchase();
}

onShow(() => loadAll());
</script>

<style lang="scss" scoped>
@import '@/styles/tokens.scss';
.page {
  min-height: 100vh;
  background: $mp-color-bg;
  padding-bottom: 120rpx;
}
.report-card {
  background: $mp-color-card;
  border-radius: $mp-radius-md;
  padding: $mp-spacing-3;
  margin-top: $mp-spacing-2;
}
.report-label {
  font-size: $mp-text-base;
  color: $mp-color-text-tertiary;
}
.report-value {
  display: block;
  margin-top: $mp-spacing-2;
  font-size: $mp-text-2xl;
  font-weight: bold;
  color: $mp-color-text-primary;
}
.report-loading {
  margin-top: $mp-spacing-2;
}
.report-error {
  margin-top: $mp-spacing-2;
}
.error-text {
  color: $mp-color-error-dark;
  font-size: $mp-text-base;
}
.muted {
  color: $mp-color-text-muted;
  font-size: $mp-text-base;
}
.empty {
  display: flex;
  justify-content: center;
  padding: 96rpx 0;
}
</style>
