// apps/miniapp/src/pages/login/index.tsx
import { useState } from 'react';
import Taro from '@tarojs/taro';
import { View, Text, Input, Button } from '@tarojs/components';
import type { AuthTokens, UserSummary } from '@app/shared';
import { apiRequest } from '@/lib/api-client';
import { useAuth } from '@/lib/auth-store';

export default function LoginPage() {
  const [email, setEmail] = useState('admin@lab.local');
  const [password, setPassword] = useState('admin123');
  const [err, setErr] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const setSession = useAuth((s) => s.setSession);

  async function submit() {
    setLoading(true);
    setErr(null);
    try {
      const tokens = await apiRequest<AuthTokens>('/auth/login', {
        method: 'POST',
        data: { email, password },
      });
      const minimalUser: UserSummary = {
        id: '',
        email,
        name: email,
        roles: [],
        labId: null,
      };
      setSession(tokens, minimalUser);
      Taro.switchTab({ url: '/pages/home/index' });
    } catch (e: any) {
      setErr(e.message ?? '登录失败');
    } finally {
      setLoading(false);
    }
  }

  return (
    <View style={{ padding: '48rpx' }}>
      <Text style={{ fontSize: '40rpx', fontWeight: 'bold' }}>实验室试剂</Text>
      <View style={{ marginTop: '32rpx' }}>
        <Text>邮箱</Text>
        <Input
          value={email}
          onInput={(e) => setEmail(e.detail.value)}
          placeholder="admin@lab.local"
          style={{
            border: '1rpx solid #ccc',
            padding: '12rpx',
            marginTop: '8rpx',
          }}
        />
      </View>
      <View style={{ marginTop: '16rpx' }}>
        <Text>密码</Text>
        <Input
          password
          value={password}
          onInput={(e) => setPassword(e.detail.value)}
          placeholder="admin123"
          style={{
            border: '1rpx solid #ccc',
            padding: '12rpx',
            marginTop: '8rpx',
          }}
        />
      </View>
      {err && (
        <View style={{ color: '#d33', marginTop: '16rpx' }}>
          <Text>{err}</Text>
        </View>
      )}
      <Button
        type="primary"
        loading={loading}
        onClick={submit}
        style={{ marginTop: '32rpx' }}
      >
        登录
      </Button>
    </View>
  );
}

// apps/miniapp-uni/src/pages/login/index.vue
<template>
  <view class="page">
    <NavBar :title="$t('common.login')" showBack />
    <view class="content p-32">
      <view class="card">
        <u-form labelPosition="top">
          <u-form-item label="Email">
            <u-input v-model="form.email" placeholder="admin@lab.local" />
          </u-form-item>
          <u-form-item label="Password">
            <u-input
              v-model="form.password"
              type="password"
              placeholder="admin123"
            />
          </u-form-item>
        </u-form>
        <view class="mt-32">
          <u-button
            type="primary"
            :text="$t('common.login')"
            :loading="loading"
            @click="onLogin"
          />
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { reactive, ref } from 'vue';
import NavBar from '@/components/nav-bar/nav-bar.vue';
import { useAuth } from '@/stores/auth';
import { i18n } from '@/locale';
import * as authApi from '@/api/modules/auth';

const auth = useAuth();
const form = reactive({ email: 'admin@lab.local', password: 'admin123' });
const loading = ref(false);

async function onLogin() {
  loading.value = true;
  try {
    const tokens = await authApi.login(form);
    auth.setTokens(tokens);
    const u = await authApi.me();
    auth.setSession(tokens, u);
    uni.showToast({ title: i18n.global.t('toast.success'), icon: 'success' });
    setTimeout(() => uni.switchTab({ url: '/pages/home/index' }), 300);
  } catch {
    /* api/request.ts 已 toast */
  } finally {
    loading.value = false;
  }
}
</script>

<style lang="scss" scoped>
.page {
  min-height: 100vh;
  background: #f5f5f5;
}
.card {
  background: #fff;
  border-radius: 16rpx;
  padding: 32rpx;
}
</style>
