// apps/miniapp-uni/src/pages/approvals/index.vue
<template>
  <view class="page">
    <NavBar :title="$t('pageTitle.approvals')" />
    <view class="content p-24">
      <view class="tabs-bar">
        <u-tabs
          :list="tabsList"
          :current="tabIndex"
          lineColor="#10b981"
          :activeStyle="{ color: '#10b981', fontWeight: 600 }"
          :inactiveStyle="{ color: '#4b5563' }"
          @click="onTabClick"
        />
      </view>

      <view v-if="tab === 'use'" class="tab-pane mt-16">
        <view v-if="reqs.length === 0" class="empty">
          <u-empty :text="$t('approvals.emptyUse')" />
        </view>
        <view v-for="r in reqs" :key="r.id" class="approval-card">
          <view class="row-between">
            <text class="approval-title">
              {{ r.reagent?.name ?? r.reagentId }}
              <text v-if="isControlled(r)" class="tag-controlled">
                【{{ $t('approvals.controlled') }}】
              </text>
            </text>
          </view>
          <text class="approval-meta block">
            {{ r.applicant?.name ?? r.applicantId }} · {{ r.quantity }}
            {{ r.unit }}
          </text>
          <text class="approval-meta block">
            {{ $t('form.purpose') }}：{{ r.purpose }}
          </text>
          <u-textarea
            v-model="comments[r.id]"
            :placeholder="$t('approvals.remark')"
            :count="false"
            :autoHeight="true"
            class="mt-8"
          />
          <view class="btn-row mt-8">
            <u-button
              size="mini"
              type="primary"
              :text="$t('approvals.approve1')"
              @click="decideUse(r.id, 'APPROVE', 1)"
            />
            <u-button
              size="mini"
              :text="$t('approvals.reject1')"
              @click="decideUse(r.id, 'REJECT', 1)"
            />
            <template v-if="isControlled(r)">
              <u-button
                size="mini"
                type="primary"
                :text="$t('approvals.approve2')"
                @click="decideUse(r.id, 'APPROVE', 2)"
              />
              <u-button
                size="mini"
                :text="$t('approvals.reject2')"
                @click="decideUse(r.id, 'REJECT', 2)"
              />
            </template>
          </view>
        </view>
      </view>

      <view v-else class="tab-pane mt-16">
        <view v-if="batchList.length === 0" class="empty">
          <u-empty :text="$t('approvals.emptyPurchase')" />
        </view>
        <view
          v-for="g in batchList"
          :key="g.batch.id"
          class="approval-card"
        >
          <text class="approval-title block">
            {{ $t('approvals.batch') }} {{ g.batch.id }}
          </text>
          <text class="approval-meta block">
            {{ $t('form.reagent') }} {{ g.batch.reagentId }} ·
            {{ g.batch.totalQty }} {{ g.batch.unit }}
          </text>
          <view class="batch-items">
            <text
              v-for="i in g.items"
              :key="i.id"
              class="batch-line block"
            >
              - {{ i.applicant?.name ?? i.applicantId }}: {{ i.quantity }}
              {{ i.unit }}（{{ i.reason }}）
            </text>
          </view>
          <u-textarea
            v-model="comments[g.batch.id]"
            :placeholder="$t('approvals.remark')"
            :count="false"
            :autoHeight="true"
            class="mt-8"
          />
          <view class="btn-row mt-8">
            <u-button
              size="mini"
              type="primary"
              :text="$t('common.approve')"
              @click="decideBatch(g.batch.id, 'APPROVE')"
            />
            <u-button
              size="mini"
              :text="$t('common.reject')"
              @click="decideBatch(g.batch.id, 'REJECT')"
            />
          </view>
        </view>
      </view>
    </view>
    <TabBar :current="2" />
    <CustomBottomArea />
  </view>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue';
import { onShow } from '@dcloudio/uni-app';
import NavBar from '@/components/nav-bar/nav-bar.vue';
import TabBar from '@/components/tab-bar/tab-bar.vue';
import CustomBottomArea from '@/components/custom-bottom-area/custom-bottom-area.vue';
import * as requestsApi from '@/api/modules/requests';
import * as purchasesApi from '@/api/modules/purchases';
import { i18n } from '@/locale';

interface Reagent {
  name: string;
  hazardLevel?: string;
  controlType?: string | null;
}
interface ReqRow {
  id: string;
  applicantId: string;
  reagentId: string;
  quantity: string;
  unit: string;
  purpose: string;
  reagent?: Reagent;
  applicant?: { name: string };
}
interface PurchaseBatch {
  id: string;
  labId: string;
  reagentId: string;
  totalQty: string;
  unit: string;
  status: string;
}
interface PurRow {
  id: string;
  applicantId: string;
  reagentId: string;
  quantity: string;
  unit: string;
  reason: string;
  reagent?: { name: string } | null;
  applicant?: { name: string } | null;
  batch?: PurchaseBatch | null;
}
interface BatchGroup {
  batch: PurchaseBatch;
  items: PurRow[];
}

const tab = ref<'use' | 'purchase'>('use');
const tabsList = computed(() => [
  { name: i18n.global.t('approvals.useTab') },
  { name: i18n.global.t('approvals.purchaseTab') },
]);
const tabIndex = computed(() => (tab.value === 'use' ? 0 : 1));
function onTabClick(item: any) {
  tab.value = item.index === 0 ? 'use' : 'purchase';
}

const reqs = ref<ReqRow[]>([]);
const groups = ref<Record<string, BatchGroup>>({});
const comments = reactive<Record<string, string>>({});

const batchList = computed(() => Object.values(groups.value));

function isControlled(r: ReqRow) {
  return (
    r.reagent?.hazardLevel === 'CONTROLLED' || !!r.reagent?.controlType
  );
}

async function refresh() {
  try {
    const [r, p] = await Promise.all([
      requestsApi.listPending(),
      purchasesApi.listPending(),
    ]);
    reqs.value = (r as ReqRow[]) ?? [];
    const g: Record<string, BatchGroup> = {};
    for (const item of (p as PurRow[]) ?? []) {
      if (!item.batch || item.batch.status !== 'PENDING') continue;
      if (!g[item.batch.id]) g[item.batch.id] = { batch: item.batch, items: [] };
      g[item.batch.id].items.push(item);
    }
    groups.value = g;
  } catch {
    /* 401 已 toast */
  }
}

async function decideUse(
  id: string,
  action: 'APPROVE' | 'REJECT',
  level: 1 | 2,
) {
  try {
    await requestsApi.decide(id, {
      action,
      level,
      comment: comments[id] ?? '',
    });
    comments[id] = '';
    await refresh();
  } catch {
    /* 401 已 toast */
  }
}

async function decideBatch(batchId: string, action: 'APPROVE' | 'REJECT') {
  try {
    await purchasesApi.decideBatch(batchId, {
      action,
      comment: comments[batchId] ?? '',
    });
    comments[batchId] = '';
    await refresh();
  } catch {
    /* 401 已 toast */
  }
}

onShow(() => refresh());
</script>

<style lang="scss" scoped>
.page {
  min-height: 100vh;
  background: #f5f5f5;
  padding-bottom: 120rpx;
}
.tabs-bar {
  background: #fff;
  border-radius: 16rpx;
  overflow: hidden;
}
.approval-card {
  background: #fff;
  border-radius: 16rpx;
  padding: 24rpx;
  margin-top: 16rpx;
}
.row-between {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.approval-title {
  font-size: 28rpx;
  font-weight: 600;
  color: #1f2937;
}
.tag-controlled {
  color: #ef4444;
  font-weight: normal;
  font-size: 24rpx;
}
.approval-meta {
  margin-top: 8rpx;
  font-size: 24rpx;
  color: #4b5563;
}
.batch-items {
  margin-top: 8rpx;
  padding: 8rpx 0;
}
.batch-line {
  font-size: 24rpx;
  color: #6b7280;
}
.btn-row {
  display: flex;
  flex-wrap: wrap;
  gap: 12rpx;
}
.block {
  display: block;
}
.empty {
  display: flex;
  justify-content: center;
  padding: 64rpx 0;
}
</style>

// apps/miniapp/src/pages/approvals/index.tsx
import { useState } from 'react';
import { useDidShow } from '@tarojs/taro';
import { View, Text, Button, Input } from '@tarojs/components';
import type {
  PurchaseBatchSummary,
  PurchaseRequestSummary,
  RequestSummary,
} from '@app/shared';
import { apiRequest } from '@/lib/api-client';

type ReqRow = RequestSummary & {
  reagent?: { name: string; hazardLevel?: string; controlType?: string | null };
  applicant?: { name: string };
};

type PurRow = PurchaseRequestSummary & {
  reagent?: { name: string } | null;
  applicant?: { name: string } | null;
  batch?: PurchaseBatchSummary | null;
};

type BatchGroup = { batch: PurchaseBatchSummary; items: PurRow[] };

export default function ApprovalsPage() {
  const [tab, setTab] = useState<'use' | 'purchase'>('use');
  const [reqs, setReqs] = useState<ReqRow[]>([]);
  const [groups, setGroups] = useState<Record<string, BatchGroup>>({});
  const [comment, setComment] = useState<Record<string, string>>({});
  const [err, setErr] = useState<string | null>(null);

  async function refresh() {
    try {
      const [r, p] = await Promise.all([
        apiRequest<ReqRow[]>('/requests?status=PENDING'),
        apiRequest<PurRow[]>('/purchases'),
      ]);
      setReqs(r);
      const g: Record<string, BatchGroup> = {};
      for (const item of p) {
        if (!item.batch || item.batch.status !== 'PENDING') continue;
        if (!g[item.batch.id]) g[item.batch.id] = { batch: item.batch, items: [] };
        g[item.batch.id].items.push(item);
      }
      setGroups(g);
      setErr(null);
    } catch (e: any) {
      setErr(e.message);
    }
  }

  useDidShow(() => {
    refresh();
  });

  async function decideUse(
    id: string,
    action: 'APPROVE' | 'REJECT',
    level: 1 | 2,
  ) {
    try {
      await apiRequest(`/requests/${id}/approvals`, {
        method: 'POST',
        data: { action, level, comment: comment[id] ?? '' },
      });
      setComment((c) => ({ ...c, [id]: '' }));
      await refresh();
    } catch (e: any) {
      setErr(e.message);
    }
  }

  async function decidePur(batchId: string, action: 'APPROVE' | 'REJECT') {
    try {
      await apiRequest(`/purchases/batches/${batchId}/approve`, {
        method: 'POST',
        data: { action, comment: comment[batchId] ?? '' },
      });
      setComment((c) => ({ ...c, [batchId]: '' }));
      await refresh();
    } catch (e: any) {
      setErr(e.message);
    }
  }

  return (
    <View style={{ padding: '24rpx' }}>
      <View style={{ display: 'flex' }}>
        <Button
          size="mini"
          type={tab === 'use' ? 'primary' : 'default'}
          onClick={() => setTab('use')}
        >
          领用
        </Button>
        <Button
          size="mini"
          type={tab === 'purchase' ? 'primary' : 'default'}
          onClick={() => setTab('purchase')}
          style={{ marginLeft: '12rpx' }}
        >
          采购
        </Button>
      </View>
      {err && (
        <Text style={{ color: '#d33', display: 'block', marginTop: '16rpx' }}>
          {err}
        </Text>
      )}

      {tab === 'use' && (
        <View style={{ marginTop: '16rpx' }}>
          {reqs.length === 0 && <Text style={{ color: '#888' }}>暂无待审批</Text>}
          {reqs.map((r) => {
            const ctrl =
              r.reagent?.hazardLevel === 'CONTROLLED' ||
              !!r.reagent?.controlType;
            return (
              <View
                key={r.id}
                style={{
                  padding: '16rpx',
                  border: '1rpx solid #eee',
                  borderRadius: '6rpx',
                  marginTop: '12rpx',
                }}
              >
                <Text style={{ fontWeight: 'bold' }}>
                  {r.reagent?.name ?? r.reagentId}
                  {ctrl ? '【管控】' : ''}
                </Text>
                <Text style={{ display: 'block', color: '#666' }}>
                  {r.applicant?.name ?? r.applicantId} · {r.quantity} {r.unit}
                </Text>
                <Text style={{ display: 'block', color: '#888' }}>
                  用途：{r.purpose}
                </Text>
                <Input
                  placeholder="备注/拒绝理由"
                  value={comment[r.id] ?? ''}
                  onInput={(e) =>
                    setComment({ ...comment, [r.id]: e.detail.value })
                  }
                  style={{
                    border: '1rpx solid #ccc',
                    padding: '10rpx',
                    marginTop: '8rpx',
                  }}
                />
                <View style={{ marginTop: '8rpx' }}>
                  <Button
                    size="mini"
                    type="primary"
                    onClick={() => decideUse(r.id, 'APPROVE', 1)}
                  >
                    一审通过
                  </Button>
                  <Button
                    size="mini"
                    onClick={() => decideUse(r.id, 'REJECT', 1)}
                    style={{ marginLeft: '8rpx' }}
                  >
                    一审拒绝
                  </Button>
                  {ctrl && (
                    <>
                      <Button
                        size="mini"
                        type="primary"
                        onClick={() => decideUse(r.id, 'APPROVE', 2)}
                        style={{ marginLeft: '8rpx' }}
                      >
                        二审通过
                      </Button>
                      <Button
                        size="mini"
                        onClick={() => decideUse(r.id, 'REJECT', 2)}
                        style={{ marginLeft: '8rpx' }}
                      >
                        二审拒绝
                      </Button>
                    </>
                  )}
                </View>
              </View>
            );
          })}
        </View>
      )}

      {tab === 'purchase' && (
        <View style={{ marginTop: '16rpx' }}>
          {Object.keys(groups).length === 0 && (
            <Text style={{ color: '#888' }}>暂无待审批批次</Text>
          )}
          {Object.entries(groups).map(([bid, g]) => (
            <View
              key={bid}
              style={{
                padding: '16rpx',
                border: '1rpx solid #eee',
                borderRadius: '6rpx',
                marginTop: '12rpx',
              }}
            >
              <Text style={{ fontWeight: 'bold' }}>批次 {bid}</Text>
              <Text style={{ display: 'block', color: '#666' }}>
                试剂 {g.batch.reagentId} · 总量 {g.batch.totalQty} {g.batch.unit}
              </Text>
              {g.items.map((i) => (
                <Text
                  key={i.id}
                  style={{ display: 'block', color: '#888' }}
                >
                  - {i.applicant?.name ?? i.applicantId}: {i.quantity} {i.unit}
                  （{i.reason}）
                </Text>
              ))}
              <Input
                placeholder="备注/拒绝理由"
                value={comment[bid] ?? ''}
                onInput={(e) =>
                  setComment({ ...comment, [bid]: e.detail.value })
                }
                style={{
                  border: '1rpx solid #ccc',
                  padding: '10rpx',
                  marginTop: '8rpx',
                }}
              />
              <View style={{ marginTop: '8rpx' }}>
                <Button
                  size="mini"
                  type="primary"
                  onClick={() => decidePur(bid, 'APPROVE')}
                >
                  通过
                </Button>
                <Button
                  size="mini"
                  onClick={() => decidePur(bid, 'REJECT')}
                  style={{ marginLeft: '8rpx' }}
                >
                  拒绝
                </Button>
              </View>
            </View>
          ))}
        </View>
      )}
    </View>
  );
}
